server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000  # cookie 30 天过期
spring:
  application:
    name: wjq-picture-backend
#  main:
#    allow-circular-references: true  #允许循环引用

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wjq_picture
    username: root
    password: wjq
    # 空间图片分表
  shardingsphere:
    datasource:
      names: wjq_picture
      wjq_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wjq_picture
        username: root
        password: wjq
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: wjq_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.wjq.wjqpicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: wjq
    timeout: 5000
  # session 配置
  session:
    timeout: 2592000  # session 30 天过期
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB  # 开放更大的文件上传体积
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        group-name: 默认
        api-rule: package
        api-rule-resources:
          - com.wjq.wjqpicturebackend.controller
logging:
  file:
    path: "logs/${spring.application.name}"
  level:
    com.wjq: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS